# Generated by Django 2.2.1 on 2019-05-25 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polyana', '0002_player_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_type', models.CharField(choices=[('GOLD', 'GOLD'), ('SILVER', 'SILVER')], db_column='type', max_length=200)),
                ('rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('currency_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polyana.Currency')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polyana.Event')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polyana.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('currency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polyana.Currency')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polyana.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.IntegerField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('currency_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polyana.Currency')),
                ('participants', models.ManyToManyField(related_name='participants', to='polyana.Player')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='winner', to='polyana.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_type', models.CharField(choices=[('5_battles', '5 battles'), ('5_wins', '5 wins'), ('first_win', 'First win')], db_column='type', max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polyana.Player')),
            ],
        ),
    ]
