# Generated by Django 2.2.1 on 2019-05-27 12:25

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polyana', '0003_achievement_battle_currency_money_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='player_id',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='battle',
            old_name='currency_id',
            new_name='currency',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='player_id',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='money',
            old_name='currency_id',
            new_name='currency',
        ),
        migrations.RenameField(
            model_name='money',
            old_name='player_id',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='currency_id',
            new_name='currency',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='event_id',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='player_id',
            new_name='player',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='participants',
        ),
        migrations.AddField(
            model_name='battle',
            name='participants',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='battle',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='winner', to='polyana.Player'),
        ),
        migrations.AlterField(
            model_name='event',
            name='payload',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True),
        ),
    ]
