# Generated by Django 2.2.1 on 2019-05-27 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polyana', '0004_erlang_adaptation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
